### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by nimaafallah** [inforastegar/Bootstrap-template#1]
salam mohandes
scripti hast ke in fake website with nginx ro automatic roo server nasb kone ?

**Comment by inforastegar** [comment]
Salam,
Khedmat ton arz konam ke man hamchin scripti nadidam haghighatan🤔
Vali az in amozesh mitonin estefade konin baraye inke khodeton install konin: (sade amozesh dade)
https://vrgl.ir/0diE0
